import { Router } from "express";
import { CreateController } from "../controller/url/createController";
import { DeleteUrlController } from "../controller/url/deleteUrlController";
import { GetUserUrlsController } from "../controller/url/getUserUrlsController";
import { RedirectUrlController } from "../controller/url/redirectUrlController";
import { authMiddleware } from "../middleware/authMiddleware";

const router = Router();
const createController = new CreateController();
const deleteUrlController = new DeleteUrlController();
const getUserUrlsController = new GetUserUrlsController();
const redirectUrlController = new RedirectUrlController();

/**
 * @swagger
 * tags:
 *   name: URLs
 *   description: URL shortening and management
 */

/**
 * @swagger
 * /api/urls/{shortCode}:
 *   get:
 *     summary: Redirect to original URL
 *     description: Redirect user to the original URL using the short code (public endpoint)
 *     tags: [URLs]
 *     parameters:
 *       - in: path
 *         name: shortCode
 *         required: true
 *         schema:
 *           type: string
 *         description: Short URL code (8 characters generated by nanoid)
 *         example: abc123De
 *     responses:
 *       302:
 *         description: Redirect to original URL
 *         headers:
 *           Location:
 *             schema:
 *               type: string
 *               format: uri
 *               example: https://www.example.com/original/long/url
 *       404:
 *         description: Short URL not found
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/Error'
 */
router.get("/:shortCode", redirectUrlController.redirect);

/**
 * @swagger
 * /api/urls:
 *   post:
 *     summary: Create a new short URL
 *     description: Create a shortened URL for the authenticated user
 *     tags: [URLs]
 *     security:
 *       - cookieAuth: []
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             required:
 *               - originalUrl
 *             properties:
 *               originalUrl:
 *                 type: string
 *                 format: uri
 *                 description: The original long URL to shorten (must be valid URL)
 *                 example: https://www.example.com/very/long/url/that/needs/shortening
 *     responses:
 *       201:
 *         description: Short URL created successfully
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 success:
 *                   type: boolean
 *                   example: true
 *                 message:
 *                   type: string
 *                   example: Short URL created successfully
 *                 data:
 *                   $ref: '#/components/schemas/Url'
 *       400:
 *         description: Invalid input - Invalid URL format
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/Error'
 *       401:
 *         description: Unauthorized - Authentication required
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/Error'
 */
router.post("/", authMiddleware, createController.create);

/**
 * @swagger
 * /api/urls:
 *   get:
 *     summary: Get all URLs for authenticated user
 *     description: Retrieve a list of all shortened URLs created by the authenticated user
 *     tags: [URLs]
 *     security:
 *       - cookieAuth: []
 *     responses:
 *       200:
 *         description: List of user's URLs retrieved successfully
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 success:
 *                   type: boolean
 *                   example: true
 *                 data:
 *                   type: array
 *                   items:
 *                     $ref: '#/components/schemas/Url'
 *       401:
 *         description: Unauthorized - Authentication required
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/Error'
 */
router.get("/", authMiddleware, getUserUrlsController.getAll);

/**
 * @swagger
 * /api/urls/{urlId}:
 *   delete:
 *     summary: Delete a short URL
 *     description: Delete a shortened URL by ID (only owner can delete)
 *     tags: [URLs]
 *     security:
 *       - cookieAuth: []
 *     parameters:
 *       - in: path
 *         name: urlId
 *         required: true
 *         schema:
 *           type: string
 *         description: URL ID to delete (CUID format)
 *         example: clxxx123456789
 *     responses:
 *       200:
 *         description: URL deleted successfully
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 success:
 *                   type: boolean
 *                   example: true
 *                 message:
 *                   type: string
 *                   example: URL deleted successfully
 *       401:
 *         description: Unauthorized - Authentication required
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/Error'
 *       403:
 *         description: Forbidden - Not the owner of this URL
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/Error'
 *       404:
 *         description: URL not found
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/Error'
 */
router.delete("/:urlId", authMiddleware, deleteUrlController.delete);

export default router;